services:
    cirici_beacon_control_client.application_manager:
        class: Cirici\BeaconControlClientBundle\Manager\ApplicationManager
        # arguments: ["@service_id", "plain_value", %parameter%]
